### ISSUE TITLE
[BUG] fresh-start.sh omits underscores in network name

### ISSUE THREAD

**Issue by mvaaltola** [evertramos/nginx-proxy-automation#271]
**Describe the bug**
Running fresh-start.sh and giving a network name containing an underscore (_) results in the network name being written to .env without the underscore.

**To Reproduce**
1. Run fresh-start.sh
2. Give a network name containing an underscore, tested with cfsi_cfsi
3. Generated .env file has NETWORK=cfsicfsi, should be cfsi_cfsi

**Expected behavior**
Write network name to .env file as given by the user in fresh_start.sh.

**Server info (please complete the following information):**
 - Linux release: Ubuntu 20.04
-  Server type: AWS EC2 c5a.16xlarge
 - Docker version: 19.03.8
 - docker-compose version: 1.25

**Logs (please send some logs):**
```
proxy-web-auto      | <> - - [14/Apr/2021:09:41:03 +0000] "GET / HTTP/2.0" 502 559 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.116 Safari/537.36"
proxy-web-auto      | 2021/04/14 09:41:03 [error] 220#220: *1 no live upstreams while connecting to upstream, client: <>, server: <>, request: "GET / HTTP/2.0", upstream: "http://<>/", host: "<>"
proxy-web-auto      | 2021/04/14 09:41:04 [error] 220#220: *1 no live upstreams while connecting to upstream, client: 91.155.152.122, server: <>, request: "GET /favicon.ico HTTP/2.0", upstream: "<>/favicon.ico", host: "<>", referrer: "https://<>/"
proxy-web-auto      | <> - - [14/Apr/2021:09:41:04 +0000] "GET /favicon.ico HTTP/2.0" 502 559 "https://<>/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.116 Safari/537.36"
```

**Additional context**
Everything works as expected after correcting the network name in .env and running `docker-compose down && docker-compose up -d`.

**Comment by evertramos** [comment]
Hello @mvaaltola, 

Thanks for your report.

Did you check the network created? We used a function from [_basescript_](https://github.com/evertramos/basescript/blob/master/string/string-remove-all-special-char-string.sh) to remove special chars in order to reduce errors, reason why it might have removed the underscore.

Please confirm if it worked, of if created a real bug in your environment. 

Thanks!

**Comment by mvaaltola** [comment]
A network *is* created, but it has the wrong name. Just tried this again by giving a network name test_test in fresh_start.sh. 

After running fresh_start.sh, running `docker network ls` shows a new network with the name testtest, so it's missing the underscore. Running `docker container inspect proxy-web-auto` shows the container to be in the testtest network.

The compose file reads the default network name for all services from the .env file. In my case simply changing the .env value to cfsi_cfsi worked, as that network already existe. It was created from another compose file and my main goal was to add the proxy to services running in that network.

In this second case, the test_test network does not already exist, and changing the value to test_test in .env expectedly results in:

```ERROR: Network test_test declared as external, but could not be found. Please create the network manually using `docker network create test_test` and try again.```

**Comment by evertramos** [comment]
Hello @mvaaltola,

Thank you again for your issue. I added enhancement once the initial idea was to create the network and not use an existing one, which turns out to create a bug if you plan to use an existing network.

So, I update the _fresh-start.sh_ script to allow _dash_ (-) and _underscore_ (_) in network names.

Best regards!
